package com.expensemanager.service;

import com.expensemanager.model.Expense;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;

@Service
public class ExportService {

    public byte[] exportToCsv(List<Expense> expenses) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (CSVPrinter printer = new CSVPrinter(
                new OutputStreamWriter(out, StandardCharsets.UTF_8),
                CSVFormat.DEFAULT.withHeader(
                        "ID", "Title", "Amount", "Currency", "Category",
                        "Type", "Status", "Date", "Submitted By", "Department",
                        "Notes", "Created At"))) {

            for (Expense e : expenses) {
                printer.printRecord(
                        e.getId(),
                        e.getTitle(),
                        e.getAmount(),
                        e.getCurrency(),
                        e.getCategory(),
                        e.getExpenseType(),
                        e.getStatus(),
                        e.getExpenseDate(),
                        e.getUser() != null ? e.getUser().getFullName() : "",
                        e.getUser() != null ? e.getUser().getDepartment() : "",
                        e.getNotes(),
                        e.getCreatedAt()
                );
            }
        }
        return out.toByteArray();
    }

    public byte[] exportToPdf(List<Expense> expenses) throws DocumentException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(document, out);
        document.open();

        // Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        Paragraph title = new Paragraph("Expense Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        document.add(title);

        // Table
        PdfPTable table = new PdfPTable(9);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        float[] widths = {0.5f, 2f, 1f, 1.2f, 1.2f, 1f, 1f, 1f, 1.5f};
        table.setWidths(widths);

        // Header
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);
        String[] headers = {"ID", "Title", "Amount", "Currency", "Category", "Type", "Status", "Date", "Submitted By"};
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(new java.awt.Color(41, 128, 185));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(6f);
            table.addCell(cell);
        }

        // Data
        Font dataFont = FontFactory.getFont(FontFactory.HELVETICA, 8);
        boolean alternate = false;
        for (Expense e : expenses) {
            java.awt.Color bg = alternate ? new java.awt.Color(245, 245, 245) : java.awt.Color.WHITE;
            addCell(table, String.valueOf(e.getId()), dataFont, bg);
            addCell(table, e.getTitle(), dataFont, bg);
            addCell(table, e.getAmount().toPlainString(), dataFont, bg);
            addCell(table, e.getCurrency(), dataFont, bg);
            addCell(table, e.getCategory().name(), dataFont, bg);
            addCell(table, e.getExpenseType().name(), dataFont, bg);
            addCell(table, e.getStatus().name(), dataFont, bg);
            addCell(table, e.getExpenseDate() != null ? e.getExpenseDate().toString() : "", dataFont, bg);
            addCell(table, e.getUser() != null ? e.getUser().getFullName() : "", dataFont, bg);
            alternate = !alternate;
        }

        document.add(table);

        // Footer
        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8);
        Paragraph footer = new Paragraph("Generated by Expense Management System | Total records: " + expenses.size(), footerFont);
        footer.setAlignment(Element.ALIGN_RIGHT);
        footer.setSpacingBefore(15);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addCell(PdfPTable table, String text, Font font, java.awt.Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text != null ? text : "", font));
        cell.setBackgroundColor(bg);
        cell.setPadding(4f);
        table.addCell(cell);
    }
}
